import { StyleSheet, Platform } from 'react-native';
import { BLUE } from '../constants';

export const styles = StyleSheet.create({
  rootPortrait: { flex: 1, backgroundColor: '#f8fafc' },
  rootLandscape: { flex: 1, flexDirection: 'row', backgroundColor: '#f8fafc' },

  headerPortrait: {
    backgroundColor: BLUE,
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'android' ? 16 : 8,
    paddingBottom: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  headerLandscape: {
    backgroundColor: BLUE,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: { color: '#fff', fontSize: 20, fontWeight: '700' },
  headerSub: { color: 'rgba(255,255,255,0.85)', fontSize: 13, marginTop: 2 },
  headerYear: { color: 'rgba(255,255,255,0.85)', fontSize: 13, marginTop: 4 },

  sideNav: { width: 76, backgroundColor: '#fff', borderRightWidth: 1, borderRightColor: '#e2e8f0' },
  sideNavHeader: { backgroundColor: BLUE, height: 52, alignItems: 'center', justifyContent: 'center' },
  sideNavHeaderIcon: { fontSize: 24 },
  sideNavItem: { alignItems: 'center', justifyContent: 'center', paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  sideNavItemActive: { backgroundColor: '#eff6ff' },
  sideNavLabel: { fontSize: 10, color: '#94a3b8', marginTop: 2, textAlign: 'center' },

  bottomNav: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    paddingBottom: Platform.OS === 'ios' ? 8 : 0,
  },
  bottomNavItem: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 10, position: 'relative' },
  navIcon: { fontSize: 22 },
  navLabel: { fontSize: 11, color: '#94a3b8', marginTop: 2 },
  navLabelActive: { color: BLUE, fontWeight: '600' },
  navIndicator: { position: 'absolute', top: 0, left: '25%', right: '25%', height: 2, backgroundColor: BLUE, borderBottomLeftRadius: 2, borderBottomRightRadius: 2 },

  mainLandscape: { flex: 1, flexDirection: 'column' },
  contentArea: { flex: 1, overflow: 'hidden' },
  screenScroll: { flex: 1 },

  overviewContent: { padding: 16, gap: 10 },
  overviewContentLandscape: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, padding: 12 },
  holidayCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  holidayCardLandscape: { width: '48%' },
  holidayCardActive: { borderColor: '#16a34a', borderWidth: 1.5, backgroundColor: '#f0fdf4' },
  holidayCardPast: { opacity: 0.5 },
  holidayCardLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  holidayCardRight: { alignItems: 'flex-end', gap: 6 },
  holidayEmoji: { fontSize: 28 },
  holidayName: { fontSize: 15, fontWeight: '600', color: '#1e293b' },
  holidayDates: { fontSize: 13, color: '#64748b', marginTop: 2 },
  badge: { backgroundColor: '#16a34a', borderRadius: 10, paddingHorizontal: 8, paddingVertical: 3 },
  badgeText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  daysChip: { alignItems: 'center', backgroundColor: '#eff6ff', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
  daysChipNumber: { fontSize: 18, fontWeight: '700', color: BLUE, lineHeight: 22 },
  daysChipLabel: { fontSize: 10, color: BLUE },
  pastLabel: { fontSize: 11, color: '#94a3b8' },
  textMuted: { color: '#94a3b8' },

  countdownPortrait: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16, padding: 24 },
  countdownLandscape: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 48, padding: 24 },
  countdownCircle: { width: 160, height: 160, borderRadius: 80, alignItems: 'center', justifyContent: 'center', borderWidth: 3 },
  countdownNumber: { fontSize: 52, fontWeight: '800', lineHeight: 60 },
  countdownLabel: { fontSize: 14, fontWeight: '500', marginTop: 2 },
  countdownEmoji: { fontSize: 48 },
  countdownInfo: { alignItems: 'center' },
  countdownTitle: { fontSize: 22, fontWeight: '700', color: '#1e293b', textAlign: 'center' },
  countdownSubtitle: { fontSize: 16, color: '#64748b', marginTop: 4 },
  countdownDate: { fontSize: 15, color: '#64748b', marginTop: 6 },
  noVacationText: { fontSize: 16, color: '#64748b', textAlign: 'center', padding: 24 },

  settingsContent: { padding: 20 },
  settingsLabel: { fontSize: 14, fontWeight: '600', color: '#374151', marginBottom: 10 },
  regionRow: { flexDirection: 'row', gap: 10 },
  regionBtn: { flex: 1, paddingVertical: 12, borderRadius: 10, borderWidth: 1.5, borderColor: '#d1d5db', alignItems: 'center', backgroundColor: '#fff' },
  regionBtnActive: { borderColor: BLUE, backgroundColor: '#eff6ff' },
  regionBtnText: { fontSize: 14, fontWeight: '500', color: '#374151' },
  regionBtnTextActive: { color: BLUE, fontWeight: '700' },
  gpsBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, backgroundColor: '#16a34a', borderRadius: 10, paddingVertical: 13, marginTop: 12 },
  gpsBtnIcon: { fontSize: 18 },
  gpsBtnText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  yearRow: { gap: 8 },
  yearBtn: { paddingVertical: 12, paddingHorizontal: 16, borderRadius: 10, borderWidth: 1.5, borderColor: '#d1d5db', backgroundColor: '#fff', alignItems: 'center' },
  yearBtnText: { fontSize: 14, fontWeight: '500', color: '#374151' },
  saveBtn: { backgroundColor: BLUE, borderRadius: 10, paddingVertical: 14, alignItems: 'center', marginTop: 24 },
  saveBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },

  aboutContent: { padding: 20, alignItems: 'center' },
  aboutPhoto: { width: 120, height: 120, borderRadius: 60, marginBottom: 16 },
  aboutTitle: { fontSize: 22, fontWeight: '700', color: '#1e293b', marginBottom: 20 },
  aboutCard: { backgroundColor: '#fff', borderRadius: 12, padding: 16, width: '100%', marginBottom: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 3, elevation: 1 },
  aboutCardTitle: { fontSize: 15, fontWeight: '700', color: '#1e293b', marginBottom: 8 },
  aboutText: { fontSize: 13, color: '#64748b', lineHeight: 20, marginBottom: 4 },
  aboutFeature: { fontSize: 13, color: '#64748b', lineHeight: 22 },
  aboutVersion: { fontSize: 12, color: '#94a3b8', marginTop: 12 },

  loadingText: { color: '#64748b', marginTop: 12, fontSize: 15 },
  errorEmoji: { fontSize: 48, marginBottom: 12 },
  errorText: { fontSize: 15, color: '#64748b', textAlign: 'center', lineHeight: 22, marginBottom: 20 },
  retryBtn: { backgroundColor: BLUE, borderRadius: 10, paddingVertical: 12, paddingHorizontal: 24 },
  retryBtnText: { color: '#fff', fontWeight: '700', fontSize: 15 },

  centered: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  scrollPad: { height: 24 },
});
